### ISSUE TITLE
1.16.5: PlayerUtil#takeFirstOnePiece initializes legacy material data

### ISSUE THREAD

**Issue by LenjoyOfficial** [kangarko/Foundation#114]
When calling PlayerUtil#takeFirstOnePiece, the server initializes legacy material support, which was mentioned in a Foundation update to be no longer needed, and it causes a little hangup. Here's the stack trace:
```
at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:257)
at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.getMaterialData(CraftMagicNumbers.java:111)
at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftItemStack.getData(CraftItemStack.java:110)
at org.mineacademy.fo.PlayerUtil.takeFirstOnePiece(PlayerUtil.java:651)
```

**Comment by kangarko** [comment]
Thanks, fixed!
