### ISSUE TITLE
Error loading SimplePlugin in catserver 

### ISSUE THREAD

**Issue by aaa8881** [kangarko/Foundation#156]
```
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.signition.riderminigame.Main'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-1f1c21e]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: Failed to remap class com.signition.riderminigame.Main
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:231) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:196) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-1f1c21e]
	... 8 more
```

seems like it's unable to load Main class by reflection. Is there any quick fix for workaround ? It works fine in spigot and paper ( obviously ) , just problematic for catserver which I'm also not very familiar, but request of one of my clients.

**Comment by aaa8881** [comment]
nvm it was java version issue. nothing to do with foundation. closing
