### ISSUE TITLE
Field issue

### ISSUE THREAD

**Issue by PedroMPagani** [kangarko/Foundation#170]
3) If needed - upload any errors to pastebin.com.

org.mineacademy.fo.ReflectionUtil$ReflectionException: No such field j in WardenSpawnTracker or its superclasses
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.ReflectionUtil.getFieldContent(ReflectionUtil.java:209)
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.ReflectionUtil.getFieldContent(ReflectionUtil.java:186)
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.remain.Remain.updateInventoryTitle(Remain.java:1523)
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.PlayerUtil.updateInventoryTitle(PlayerUtil.java:631)
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.PlayerUtil.updateInventoryTitle(PlayerUtil.java:598)
[22:20:39 INFO]: at pocketbeacon-1.0.4-shaded.jar//org.mineacademy.fo.menu.Menu.animateTitle(Menu.java:685)

**Comment by kangarko** [comment]
Thanks, solved in 6.0.3
