### ISSUE TITLE
ItemsAdder dependency failing

### ISSUE THREAD

**Issue by aaa8881** [kangarko/Foundation#213]
Pufferfish #61 ( 1.19.3 fork ) 
ItemsAdder 3.4.0-r2 ( latest )
Foundation 6.3.2

Also, HookManager.loadDependencies() is hardcoded in SimplePlugin enable. This can happen anytime. Is it possible to toggleable by default in futures versions?

```
[12:12:22 ERROR]: Error occurred while enabling SigLib v1.2.7-SNAPSHOT (Is it up to date?)
com.signition.SigLib.lib.fo.ReflectionUtil$ReflectionException: Could not find class: dev.lone.itemsadder.api.FontImages.FontImageWrapper
	at com.signition.SigLib.lib.fo.ReflectionUtil.lookupClass(ReflectionUtil.java:641) ~[SigLib.jar:?]
	at com.signition.SigLib.lib.fo.model.ItemsAdderHook.<init>(HookManager.java:3772) ~[SigLib.jar:?]
	at com.signition.SigLib.lib.fo.model.HookManager.loadDependencies(HookManager.java:222) ~[SigLib.jar:?]
	at com.signition.SigLib.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:298) ~[SigLib.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[pufferfish-1.19.3.jar:git-Pufferfish-60]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.19.3.jar:git-Pufferfish-60]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[pufferfish-1.19.3.jar:git-Pufferfish-60]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[pufferfish-1.19.3.jar:git-Pufferfish-60]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.19.3.jar:git-Pufferfish-60]
```

**Comment by kangarko** [comment]
The given class is found at the ItemsAdder source, I can't reproduce it. Do you get the same error just running Paper? To fix it with the same logic I'd have to add silence errors for all plugins listen in HookManager which is unfeasible.

![a](https://i.imgur.com/BCK59sB.png)
