### ISSUE TITLE
EssentialsX Dependency not loading.

### ISSUE THREAD

**Issue by DrogazDev** [kangarko/Foundation#253]
Hey, im new to Foundation and just started using it, it was testing it on my development server and everything worked fine, until i put it on the live server and i got a error for a Dependency not loading. I have pasted the error that has been logged from the error.log underneath. Is their a way to disable Essentials Dependency because im not using but but it keeps me from testing now.

More Information: 
Error while loading FineMC dependencies!
ClassCastException class com.earth2me.essentials.Essentials cannot be cast to class com.earth2me.essentials.Essentials (com.earth2me.essentials.Essentials is in unnamed module of loader 'EssentialsX-2.21.0-dev+17-79449ef.jar' @6e427fd3; com.earth2me.essentials.Essentials is in unnamed module of loader 'FineMC-1.0-SNAPSHOT.jar' @6a983615)
	 at FineMC-1.0-SNAPSHOT.jar//org.mineacademy.fo.model.EssentialsHook.<init>(HookManager.java:1877)
	 at FineMC-1.0-SNAPSHOT.jar//org.mineacademy.fo.model.HookManager.loadDependencies(HookManager.java:193)
	 at FineMC-1.0-SNAPSHOT.jar//org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:277)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
	 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
	 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
	 at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
	 at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
	 at org.bukkit.craftbukkit.v1_19_R3.CraftServer.reload(CraftServer.java:1039)
	 at org.bukkit.Bukkit.reload(Bukkit.java:952)
	 at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
	 at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:929)
	 at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
	 at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	 at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:322)
	 at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:306)

**Comment by kangarko** [comment]
Try to do a fresh start instead of reloading. Looks like something went wrong in the reload process.
