### ISSUE TITLE
1.20.1: animation

### ISSUE THREAD

**Issue by TheRedEnd2000** [kangarko/Foundation#257]
Hello,

So i used this extention for my plugin

When i create my inventory and it opens an animation with glass starts
wenn i then go with a button in an extra menu and use the door to go back the animation is not longer there

This is my code:

````java
@Override
    protected void onPostDisplay(Player viewer) {
        animate(40, new MenuRunnable() {
            boolean toggle = true;
            @Override
            public void run() {
                int[] glass = new int[]{0,1,2,6,7,8,9,17,36,44,45,46,47,51,52,53};
                for (int i = 0; i<glass.length;i++)
                    setItem(glass[i],ItemCreator.of(toggle ? CompMaterial.LIME_STAINED_GLASS_PANE : CompMaterial.WHITE_STAINED_GLASS_PANE,"§c").make());
                int[] glass2 = new int[]{3,5,18,26,27,35,48,50};
                for (int i = 0; i<glass2.length;i++)
                    setItem(glass2[i],ItemCreator.of(!toggle ? CompMaterial.LIME_STAINED_GLASS_PANE : CompMaterial.WHITE_STAINED_GLASS_PANE,"§c").make());
                toggle = !toggle;
            }
        });
    }
````    
hope it get fixed
    
I have one question left: is there a wiki to see all the funktions of foundation or a information how to use the extention?
    
Your siencly

**Comment by kangarko** [comment]
Hey!

Try using "true" as the last argument in your submenu constructor that returns back to the animated menu. That will toggle making a new instance of the parent menu. Make sure to override newInstance() method in the parent menu:

![a](https://i.imgur.com/5YYeksO.png)

**Comment by kangarko** [comment]
No right now there is no wiki of Foundation.

**Comment by TheRedEnd2000** [comment]
Is it possible to add one?

**Comment by TheRedEnd2000** [comment]
So if i made it true and then what to go back i  get this error

	at de.theredend2000.hideandseek.commands.ArenaCommands.onCommand(ArenaCommands.java:93) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
[01:58:57] [Server thread/ERROR]: HideAndSeek 1.0 encountered a NoSuchMethodException! Please check your error.log and report this issue with the information in that file. Running CraftBukkit 1.20.1-R0.1-SNAPSHOT and Java 17.0.3
[01:58:57] [Server thread/WARN]: org.mineacademy.fo.exception.FoException: Report: Could not get constructor of class de.theredend2000.hideandseek.inventorys.GameSettingsInventory with parameters 
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.ReflectionUtil.getConstructor(ReflectionUtil.java:182)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.ReflectionUtil.instantiate(ReflectionUtil.java:515)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.menu.Menu.newInstance(Menu.java:383)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.menu.button.ButtonReturnBack.onClickedInMenu(ButtonReturnBack.java:94)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.menu.Menu.onButtonClick(Menu.java:1109)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.menu.MenuPagged.onButtonClick(MenuPagged.java:564)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.menu.MenuListener.onMenuClick(MenuListener.java:96)
[01:58:57] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:58:57] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:58:57] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:58:57] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[01:58:57] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[01:58:57] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:58:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[01:58:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2783)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019)
[01:58:57] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[01:58:57] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[01:58:57] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: de.theredend2000.hideandseek.inventorys.GameSettingsInventory.<init>()
[01:58:57] [Server thread/WARN]: 	at java.base/java.lang.Class.getConstructor0(Unknown Source)
[01:58:57] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredConstructor(Unknown Source)
[01:58:57] [Server thread/WARN]: 	at org.mineacademy.fo.ReflectionUtil.getConstructor(ReflectionUtil.java:174)
[01:58:57] [Server thread/WARN]: 	... 31 more
[01:58:57] [Server thread/ERROR]: HideAndSeek 1.0 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running CraftBukkit 1.20.1-R0.1-SNAPSHOT and Java 17.0.3
[01:58:57] [Server thread/INFO]: org.mineacademy.fo.exception.FoException: Report: Could not instantiate menu of class de.theredend2000.hideandseek.inventorys.GameSettingsInventory, override the method 'newInstance()' or ensure you have a public constructor which takes only one parameter 
[01:58:57] [Server thread/INFO]: 	at org.mineacademy.fo.menu.Menu.newInstance(Menu.java:396)
[01:58:57] [Server thread/INFO]: 	at org.mineacademy.fo.menu.button.ButtonReturnBack.onClickedInMenu(ButtonReturnBack.java:94)
[01:58:57] [Server thread/INFO]: 	at org.mineacademy.fo.menu.Menu.onButtonClick(Menu.java:1109)
[01:58:57] [Server thread/INFO]: 	at org.mineacademy.fo.menu.MenuPagged.onButtonClick(MenuPagged.java:564)
[01:58:57] [Server thread/INFO]: 	at org.mineacademy.fo.menu.MenuListener.onMenuClick(MenuListener.java:96)
[01:58:57] [Server thread/INFO]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:58:57] [Server thread/INFO]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[01:58:57] [Server thread/INFO]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[01:58:57] [Server thread/INFO]: 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[01:58:57] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[01:58:57] [Server thread/INFO]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:58:57] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[01:58:57] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[01:58:57] [Server thread/INFO]: [HideAndSeek] !-----------------------------------------------------!
[01:58:57] [Server thread/INFO]: [HideAndSeek]  Error clicking in menu SpawnsMenu{}
[01:58:57] [Server thread/INFO]: [HideAndSeek] !-----------------------------------------------------!

is this a code error or foundation error?

**Comment by TheRedEnd2000** [comment]
can i somehow get the newInstance() with arguments 
or is it possible to make a border of glas or somethink like that

**Comment by kangarko** [comment]
No, the new instance must be without arguments.

But you can just keep the arguments from your main constructor as fields in the class, and then pass them inside the new instance like this:

![a](https://i.imgur.com/B796Hqu.png)
