### ISSUE TITLE
1.20.4: Plugin cannot load Depedencies

### ISSUE THREAD

**Issue by Luispupuis** [kangarko/Foundation#292]
Hello,
I have an error in the console for my Plugin.
Can anyone help me? i can also send the src.
Thanks
[11:07:45 INFO]: [Auctions] !-----------------------------------------------------!
[11:07:45 INFO]: [Auctions]  Error while loading Auctions dependencies!
[11:07:45 INFO]: [Auctions] !-----------------------------------------------------!
[11:07:45 ERROR]: Auctions 1.0-SNAPSHOT encountered a ClassCastException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.4-R0.1-SNAPSHOT and Java 20.0.1
[11:07:45 ERROR]: Error occurred while enabling Auctions v1.0-SNAPSHOT (Is it up to date?)
java.lang.ClassCastException: class com.onarandombox.MultiverseCore.MultiverseCore cannot be cast to class com.onarandombox.MultiverseCore.MultiverseCore (com.onarandombox.MultiverseCore.MultiverseCore is in unnamed module of loader 'Multiverse-Core-4.3.1 (8).jar' @492471dc; com.onarandombox.MultiverseCore.MultiverseCore is in unnamed module of loader 'Auctions-1.0-SNAPSHOT.jar' @75daf108)
        at org.mineacademy.fo.model.MultiverseHook.<init>(HookManager.java:2084) ~[Auctions-1.0-SNAPSHOT.jar:?]
        at org.mineacademy.fo.model.HookManager.loadDependencies(HookManager.java:247) ~[Auctions-1.0-SNAPSHOT.jar:?]
        at org.mineacademy.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:275) ~[Auctions-1.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-388]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-388]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by notmyidea** [comment]
What did you even try to do ? Does your plugin depends on Multiverse-Core or have you shaded it? You should also attach your src.

**Comment by Luispupuis** [comment]
> What did you even try to do ? Does your plugin depend on Multiverse-Core or have you shaded it? You should also attach your src.

Animated GUI
[src.zip](https://github.com/user-attachments/files/15524736/src.zip)

**Comment by notmyidea** [comment]
You don't depend on the plugin anywhere: https://www.spigotmc.org/threads/plugin-dependencies.507658/
Make sure Multiverse is installed correctly too.
