### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by WhipMeGrandmaa** [kangarko/Foundation#305]
Error when sending toasts:

com.google.gson.JsonSyntaxException: Unsupported icon type, currently only items are supported (add 'item' key)
        at net.minecraft.advancements.DisplayInfo.getIcon(DisplayInfo.java:108) ~[?:?]
        at net.minecraft.advancements.DisplayInfo.fromJson(DisplayInfo.java:94) ~[?:?]
        at net.minecraft.advancements.Advancement$Builder.fromJson(Advancement.java:390) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.loadAdvancement(CraftMagicNumbers.java:333) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.oraclepvp.oraclestatistics.lib.remain.AdvancementAccessor.loadAdvancement(Remain.java:3424) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.lib.remain.AdvancementAccessor.show(Remain.java:3414) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.lib.remain.Remain.sendToast(Remain.java:2449) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.model.Effects.executeOnSender(Effects.java:119) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.model.Effects.executeOnSender(Effects.java:80) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.model.StatisticType.onIncrement(StatisticType.java:84) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.util.IncrementUtil.onIncrement(IncrementUtil.java:32) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.util.IncrementUtil.onIncrement(IncrementUtil.java:21) ~[OracleStatistics-1.0.0.jar:?]
        at net.oraclepvp.oraclestatistics.listener.BlockRegenListener.onBlockRegenMine(BlockRegenListener.java:25) ~[OracleStatistics-1.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor768.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:git-Pufferfish-26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.oraclepvp.oracleblockregen.lib.Common.callEvent(Common.java:2830) ~[OracleBlockRegen-1.0.0.jar:?]
        at net.oraclepvp.oracleblockregen.model.RegenBlock.handleBreak(RegenBlock.java:80) ~[OracleBlockRegen-1.0.0.jar:?]
        at net.oraclepvp.oracleblockregen.model.RegenBlock.handleBreak(RegenBlock.java:58) ~[OracleBlockRegen-1.0.0.jar:?]
        at net.oraclepvp.oracleblockregen.listener.PlayerListener.onBlockBreak(PlayerListener.java:73) ~[OracleBlockRegen-1.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:git-Pufferfish-26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1928) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1317) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1310) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1288) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1176) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]

**Comment by StarozytnySky** [comment]
Update your server to latest version 1.20 in this case is 1.20.6, old subversions is not supported.

Previous i made PR about this, you can check here: https://github.com/kangarko/Foundation/pull/298

**Comment by kangarko** [comment]
Thanks. Update or wait for us to update. I will edit the line by @StarozytnySky to 

````java
if (MinecraftVersion.atLeast(V.v1_21) || (MinecraftVersion.equals(V.v1_20) && MinecraftVersion.getSubversion() >= 5))
````

to make it work on legacy version too.
