### ISSUE TITLE
1.20.4: Failure to Convert SerializedMap to JSON String in Certain Situations

### ISSUE THREAD

**Issue by Backas03** [kangarko/Foundation#341]
A ``JSONParseException`` occurs when converting the serialized map, read from the YAML data, into a JSON string.
foundation version: `6.5.8`
```yaml
item_data:
  action: "RECEIVE"
  name: "&f𣀌 &6&lInfo"
  material: PAPER
  # custom_model_data: 2022
  desc:
    - ""
    - "&7Status&8: {manufacturing_status}"
    - "&7Processed Item&8: {current_recipe_name}"
    - "&7Progress&8: &a{progression}&8/&2{complete_progression}"
    - ""
    - "&f𢀓 &b&lReward"
    - "   {current_output_reward}"
    - ""
    - "&f𣀆 &c&lFailure Condition"
    - "   &7Progress &a86400 or more"
    - ""
    # - "Additional Reward"
    # - "{current_output_extra_reward}"
```
**StackTrace**
(The foundation code has been shaded during our project's build process and relocated to ``com.signition.common.lib``.)
```
[10:48:09 ERROR]: SigCommonCore 1.2.8 encountered a JSONParseException! Please check your error.log and report this issue with the information in that file. Running Paper 1.20.4-R0.1-SNAPSHOT and Java 21.0.5
[10:48:09 INFO]: com.signition.common.lib.fo.jsonsimple.JSONParseException: The unexpected character (c) was found at position 4. Fix the parsable string and try again.
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.jsonsimple.Yylex.yylex(Yylex.java:629)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.jsonsimple.JSONParser.lexNextToken(JSONParser.java:472)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.jsonsimple.JSONParser.deserialize(JSONParser.java:142)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.jsonsimple.JSONParser.deserialize(JSONParser.java:121)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.jsonsimple.JSONParser.deserialize(JSONParser.java:330)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.SerializeUtil.addJsonElement(SerializeUtil.java:347)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.SerializeUtil.serialize(SerializeUtil.java:223)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.lib.fo.collection.SerializedMap.toJson(SerializedMap.java:943)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.config.MachineConfigReader.readGUIListData(MachineConfigReader.java:404)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.config.MachineConfigReader.read(MachineConfigReader.java:65)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.config.MachineConfigLoader.load(MachineConfigLoader.java:56)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.config.MachineConfig.reload(MachineConfig.java:30)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.controller.MachineController.reload(MachineController.java:51)
[10:48:09 INFO]:      at SigCommonCore.jar//com.signition.common.module.machine.command.CmdMachineAdmin.lambda$onCommand$0(CmdMachineAdmin.java:117)
[10:48:09 INFO]:      at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:49:22 INFO]: [SigCommonCore] !-----------------------------------------------------!
[10:49:22 INFO]: [SigCommonCore]  Failed to deserialize JSON collection from string:    {current_output_reward}
[10:49:22 INFO]: [SigCommonCore] !-----------------------------------------------------!
```
**Code**
![image](https://github.com/user-attachments/assets/36942fb0-405e-484d-abfe-d77a14ce2490)
```java
SerializedMap map = ...;
String jsonSring = map.toJson(); // error
```

**Comment by Backas03** [comment]
+  If the space before ``{current_output_reward}`` is removed, no error occurs.

**Comment by kangarko** [comment]
Are you sure it's a standard unicode space? It might have been some non-English unsupported character by snakeYAML parser.
