### ISSUE TITLE
Issue with MenuButtons on 1.15

### ISSUE THREAD

**Issue by crazyeightlikesapples** [kangarko/Foundation#7]
Hello, I wrote a program with Foundations that works fine on 1.14.4 but most of the buttons don't work on 1.15. I tried with spigot and paper, but paper was the only one that actually gave me an error message. This happens when I try to press a button

 java.lang.NullPointerException
[15:53:37 INFO]: at org.bukkit.inventory.ItemStack.isSimilar(ItemStack.java:275)
[15:53:37 INFO]: at org.bukkit.inventory.ItemStack.equals(ItemStack.java:256)
[15:53:37 INFO]: at org.mineacademy.fo.menu.Menu.getButton(Menu.java:287)
[15:53:37 INFO]: at org.mineacademy.fo.menu.MenuListener.onMenuClick(MenuListener.java:71)
[15:53:37 INFO]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor63.execute(Unknown Source)
[15:53:37 INFO]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:53:37 INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:53:37 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:53:37 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePlugin

**Comment by kangarko** [comment]
@crazyeightlikesapples please provide your sample code

@JavaFactoryDev could you please have a look?

**Comment by JavaFactoryDev** [comment]
Can't do anything until sample code is provided.

**Comment by JavaFactoryDev** [comment]
User doesn't respond
